export const GET_PRODUCT_DATA_LOADING = "GET_PRODUCT_DATA_LOADING"
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS"
export const GET_PRODUCT_DATA_ERROR = "GET_PRODUCT_DATA_ERROR"

export const SORT_PRICE = "SORT_PRICE"